import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from "next/script";
import {Provider} from "react-redux";
import StoreProvider from "@/lib/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <nav className="navbar navbar-expand-lg bg-primary">
            <div className="container">
                <div>
                    <ul className="navbar-nav ms-auto">
                        <li className="nav-item"><Link className="text-white nav-link" href="/">Home</Link></li>
                        <li className="nav-item"><Link className="text-white nav-link" href="/login">Login/Register</Link></li>

                    </ul>
                </div>
            </div>
        </nav>

        <main>
            <StoreProvider>{children}</StoreProvider>
        </main>

        </body>
        </html>
    );
}
